export const IPC_CHANNELS = {
  bootstrap: 'herdr:bootstrap',
  startServer: 'herdr:start-server',
  command: 'herdr:command',
  query: 'herdr:query',
  stageChatImages: 'desktop:stage-chat-images',
  readPreferences: 'desktop:preferences-read',
  writePreferences: 'desktop:preferences-write',
  chooseBinary: 'herdr:choose-binary',
  resetBinary: 'herdr:reset-binary',
  remoteEngineApply: 'remote-engine:apply',
  remoteEngineStatus: 'remote-engine:status',
  sessionEvent: 'herdr:session-event',
  terminalOpen: 'herdr:terminal-open',
  terminalInput: 'herdr:terminal-input',
  terminalResize: 'herdr:terminal-resize',
  terminalScroll: 'herdr:terminal-scroll',
  terminalClose: 'herdr:terminal-close',
  terminalEvent: 'herdr:terminal-event',
  desktopAction: 'desktop:action',
  openExternal: 'desktop:open-external',
} as const;
