import type { AgentInfo, SessionSnapshot } from '@/shared/herdr';

const agent = (
  paneId: string,
  workspaceId: string,
  tabId: string,
  status: AgentInfo['agent_status'],
  sequence: number,
): AgentInfo => ({
  terminal_id: `terminal-${paneId}`,
  name: paneId === 'p1' ? 'reviewer' : undefined,
  agent: 'codex',
  display_agent: 'Codex',
  agent_status: status,
  screen_detection_skipped: false,
  state_labels: {},
  tokens: {},
  workspace_id: workspaceId,
  tab_id: tabId,
  pane_id: paneId,
  focused: paneId === 'p1',
  launch_pending: false,
  interactive_ready: true,
  state_change_seq: sequence,
  revision: sequence,
});

export const snapshot: SessionSnapshot = {
  version: '0.8.0',
  protocol: 7,
  focused_workspace_id: 'w1',
  focused_tab_id: 't1',
  focused_pane_id: 'p1',
  workspaces: [
    {
      workspace_id: 'w2',
      number: 2,
      label: 'Docs',
      focused: false,
      pane_count: 1,
      tab_count: 1,
      active_tab_id: 't3',
      agent_status: 'idle',
      tokens: {},
    },
    {
      workspace_id: 'w1',
      number: 1,
      label: 'Desktop',
      focused: true,
      pane_count: 2,
      tab_count: 2,
      active_tab_id: 't1',
      agent_status: 'blocked',
      tokens: {},
    },
  ],
  tabs: [
    {
      tab_id: 't2',
      workspace_id: 'w1',
      number: 2,
      label: 'Tests',
      focused: false,
      pane_count: 1,
      agent_status: 'done',
    },
    {
      tab_id: 't3',
      workspace_id: 'w2',
      number: 1,
      label: 'Guide',
      focused: false,
      pane_count: 1,
      agent_status: 'idle',
    },
    {
      tab_id: 't1',
      workspace_id: 'w1',
      number: 1,
      label: 'Build',
      focused: true,
      pane_count: 1,
      agent_status: 'blocked',
    },
  ],
  panes: [],
  layouts: [],
  agents: [agent('p2', 'w1', 't2', 'done', 2), agent('p1', 'w1', 't1', 'blocked', 3)],
};
